### ISSUE TITLE
Broken dependency preventing Android build

### ISSUE THREAD

**Issue by IgorBelyayev** [playn/playn-samples#5]
In the Android sub project, there's a dependency on [`maven-junction-plugin`](https://mvnrepository.com/artifact/com.pyx4j/maven-junction-plugin/1.0.3)  which itself depends on a dependency called `sysinternals » junction`. 

`sysinternals » junction` was entirely removed from Maven due to a [security issue](https://issues.sonatype.org/browse/MVNCENTRAL-1365) and so now the Android project can't build because it can't find this dependency.

**Comment by samskivert** [comment]
Thanks, fixed.
